from .nodes import NODE_CLASS_MAPPINGS as _NCM_BASE, NODE_DISPLAY_NAME_MAPPINGS as _NDM_BASE
from .nodes_highlow import NODE_CLASS_MAPPINGS as _NCM_HL, NODE_DISPLAY_NAME_MAPPINGS as _NDM_HL
from .nodes_wan import NODE_CLASS_MAPPINGS as _NCM_WAN, NODE_DISPLAY_NAME_MAPPINGS as _NDM_WAN
from .nodes_looper_v2 import NODE_CLASS_MAPPINGS as _NCM_V2, NODE_DISPLAY_NAME_MAPPINGS as _NDM_V2
from .nodes_wan_v2 import NODE_CLASS_MAPPINGS as _NCM_WANV2, NODE_DISPLAY_NAME_MAPPINGS as _NDM_WANV2

NODE_CLASS_MAPPINGS = {**_NCM_BASE, **_NCM_HL, **_NCM_WAN, **_NCM_V2, **_NCM_WANV2}
NODE_DISPLAY_NAME_MAPPINGS = {**_NDM_BASE, **_NDM_HL, **_NDM_WAN, **_NDM_V2, **_NDM_WANV2}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
