from .nodes_wan import NODE_CLASS_MAPPINGS as _NCM_WAN, NODE_DISPLAY_NAME_MAPPINGS as _NDM_WAN
from .nodes_wan_v2 import NODE_CLASS_MAPPINGS as _NCM_WANV2, NODE_DISPLAY_NAME_MAPPINGS as _NDM_WANV2

NODE_CLASS_MAPPINGS = {**_NCM_WAN, **_NCM_WANV2}
NODE_DISPLAY_NAME_MAPPINGS = {**_NDM_WAN, **_NDM_WANV2}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
